WRAP_POLAR_WIDTH = 600
WRAP_POLAR_HEIGHT = 100

DEGREE = WRAP_POLAR_WIDTH

CLOCK_FACE_MIN_RADIUS_CLOCK = 300
CLOCK_FACE_MAX_RADIUS_CLOCK = 400

CLOCK_FACE_MIN_RADIUS_TIMER = 100
CLOCK_FACE_MAX_RADIUS_TIMER = 200

CLOCK_FACE_MIN_DIST = 100
CLOCK_FACE_PARAM_1 = 30
CLOCK_FACE_PARAM_2 = 50