DEFAULT_WRAP_POLAR_WIDTH = 600
DEFAULT_WRAP_POLAR_HEIGHT = 100
DEFAULT_WRAP_POLAR_HEIGHT_ERROR = 25

DEGREE = DEFAULT_WRAP_POLAR_WIDTH

MIN_RADIUS_CLOCK = 300
MAX_RADIUS_CLOCK = 400

MIN_RADIUS_TIMER = 100
MAX_RADIUS_TIMER = 200

MIN_RADIUS_SMALL_TIMER = 30
MAX_RADIUS_SMALL_TIMER = 70

CLOCK_FACE_MIN_DIST = 100
CLOCK_FACE_PARAM_1 = 30
CLOCK_FACE_PARAM_2 = 50

CLOCK_FACE_DEFAULT_BLURRING = 25