DEFAULT_WRAP_POLAR_WIDTH = 600
DEFAULT_WRAP_POLAR_HEIGHT = 100
DEFAULT_WRAP_POLAR_HEIGHT_ERROR = 25

DEGREE = DEFAULT_WRAP_POLAR_WIDTH

MIN_RADIUS_CLOCK = 300
MAX_RADIUS_CLOCK = 400

MIN_RADIUS_TIMER = 125
MAX_RADIUS_TIMER = 140

SMALL_TIMER_MIN_RADIUS = 35
SMALL_TIMER_MAX_RADIUS = 40

CLOCK_MIN_DIST = 100
CLOCK_PARAM_1 = 30
CLOCK_PARAM_2 = 50

TIMER_MIN_DIST = 20

CLOCK_FACE_DEFAULT_BLURRING = 25